import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useQuery } from "@apollo/client";
import { TEST } from "../../utils/queries";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { data, loading, error } = useQuery(TEST);
  if (loading) return <div>Loading...</div>;
  console.log("data", data);
  return (
    <>
      <Head>
        <title>Meloroids data</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>DATA</main>
    </>
  );
}
