import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Meloroids data</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <div className="row">
          <div className="container">
            <h2 className="header">Queries:</h2>
            <Link href="/artists" className="link">
              All Artists
            </Link>
          </div>
          <div className="container">
            {" "}
            <h2 className="header">Mutations:</h2>
            <div className="options-wrapper">
              <Link href="/album-to-artist" className="link">
                Add albums to artists
              </Link>
              <Link href="/songs-to-albums" className="link">
                Add songs to albums
              </Link>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
